/* *****************************************************
   THIS IS AN AUTOMATICALLY GENERATED FILE. DO NOT EDIT.
   *****************************************************

   Generated by:
     cctbx_project/boost_adaptbx/SConscript
 */

#ifndef BOOST_ADAPTBX_TYPE_ID_EQ_H
#define BOOST_ADAPTBX_TYPE_ID_EQ_H

#define BOOST_ADAPTBX_TYPE_ID_SIZE_T_EQ_UNSIGNED_LONG

#endif // GUARD
