github:
  user_or_org: cci-lbl
  repo_name: xfel-feedstock
  branch_name: main
  tooling_branch_name: main
channels:
  targets:
    - [xfel, main]

azure:
  user_or_org: cctbx-release
  project_name: feedstock-builds
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
test_on_native_only: true
test: native
